
SHELF = 1
FORKLIFT = 4
EXIT = 3
PRODUCT = 2
PRODUCT_CATCH = 5
EMPTY = 0

COLORSHELF ='green'
COLORSHELFPRODUCT = 'gray'
COLORSHELFPRODUCTCATCH = 'black'
COLORFORKLIFT = 'red'
COLOREXIT = 'blue'
COLOREMPTY = 'white'